# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 18:44
from __future__ import unicode_literals

import apps.store.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20171215_1844'),
        ('login', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, validators=[apps.store.models.validateLengthGreaterThanTwo])),
                ('store_number', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50, validators=[apps.store.models.validateEmail])),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='agency.Agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
